// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: admins.sql

package db

import (
	"context"
)

const createAdmin = `-- name: CreateAdmin :exec
INSERT INTO admins (user_id)
VALUES ($1)
`

func (q *Queries) CreateAdmin(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, createAdmin, userID)
	return err
}

const isAdminExists = `-- name: IsAdminExists :one
SELECT user_id FROM admins
WHERE user_id = $1
`

func (q *Queries) IsAdminExists(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, isAdminExists, userID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
