// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package db

import (
	"context"
)

const createFile = `-- name: CreateFile :exec
INSERT INTO files (file_id, file_key, file_type, uploaded_by)
VALUES ($1, $2, $3, $4)
`

type CreateFileParams struct {
	FileID     string
	FileKey    string
	FileType   FileTypeEnum
	UploadedBy int64
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) error {
	_, err := q.db.Exec(ctx, createFile,
		arg.FileID,
		arg.FileKey,
		arg.FileType,
		arg.UploadedBy,
	)
	return err
}

const getFileByKey = `-- name: GetFileByKey :one
SELECT file_id, file_key, file_type, uploaded_by, uploaded_at FROM files
WHERE file_key = $1
`

func (q *Queries) GetFileByKey(ctx context.Context, fileKey string) (File, error) {
	row := q.db.QueryRow(ctx, getFileByKey, fileKey)
	var i File
	err := row.Scan(
		&i.FileID,
		&i.FileKey,
		&i.FileType,
		&i.UploadedBy,
		&i.UploadedAt,
	)
	return i, err
}

const isFileExistsByKey = `-- name: IsFileExistsByKey :one
SELECT file_id FROM files
WHERE file_key = $1
`

func (q *Queries) IsFileExistsByKey(ctx context.Context, fileKey string) (string, error) {
	row := q.db.QueryRow(ctx, isFileExistsByKey, fileKey)
	var file_id string
	err := row.Scan(&file_id)
	return file_id, err
}

const updateFile = `-- name: UpdateFile :exec
UPDATE files
SET file_id = $1,
    file_type = $2,
    uploaded_by = $3,
    uploaded_at = now()
WHERE file_key = $4
`

type UpdateFileParams struct {
	FileID     string
	FileType   FileTypeEnum
	UploadedBy int64
	FileKey    string
}

func (q *Queries) UpdateFile(ctx context.Context, arg UpdateFileParams) error {
	_, err := q.db.Exec(ctx, updateFile,
		arg.FileID,
		arg.FileType,
		arg.UploadedBy,
		arg.FileKey,
	)
	return err
}
