// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: heroes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyHeroDelta = `-- name: ApplyHeroDelta :one
UPDATE heroes
SET hp = LEAST(100, GREATEST(0, hp + $2)),
    energy = LEAST(100, GREATEST(0, energy + $3)),
    hunger = LEAST(100, GREATEST(0, hunger + $4)),
    thirst = LEAST(100, GREATEST(0, thirst + $5)),
    radiation = LEAST(100, GREATEST(0, radiation + $6))
WHERE user_id = $1
RETURNING hero_id, user_id, hp, energy, hunger, thirst, radiation
`

type ApplyHeroDeltaParams struct {
	UserID    int64
	Hp        int32
	Energy    int32
	Hunger    int32
	Thirst    int32
	Radiation int32
}

func (q *Queries) ApplyHeroDelta(ctx context.Context, arg ApplyHeroDeltaParams) (Hero, error) {
	row := q.db.QueryRow(ctx, applyHeroDelta,
		arg.UserID,
		arg.Hp,
		arg.Energy,
		arg.Hunger,
		arg.Thirst,
		arg.Radiation,
	)
	var i Hero
	err := row.Scan(
		&i.HeroID,
		&i.UserID,
		&i.Hp,
		&i.Energy,
		&i.Hunger,
		&i.Thirst,
		&i.Radiation,
	)
	return i, err
}

const createHero = `-- name: CreateHero :exec
INSERT INTO heroes (hero_id, user_id)
VALUES ($1, $2)
`

type CreateHeroParams struct {
	HeroID pgtype.UUID
	UserID int64
}

func (q *Queries) CreateHero(ctx context.Context, arg CreateHeroParams) error {
	_, err := q.db.Exec(ctx, createHero, arg.HeroID, arg.UserID)
	return err
}

const getHeroByUser = `-- name: GetHeroByUser :one
SELECT hero_id, user_id, hp, energy, hunger, thirst, radiation FROM heroes
WHERE user_id = $1
`

func (q *Queries) GetHeroByUser(ctx context.Context, userID int64) (Hero, error) {
	row := q.db.QueryRow(ctx, getHeroByUser, userID)
	var i Hero
	err := row.Scan(
		&i.HeroID,
		&i.UserID,
		&i.Hp,
		&i.Energy,
		&i.Hunger,
		&i.Thirst,
		&i.Radiation,
	)
	return i, err
}

const isHeroExists = `-- name: IsHeroExists :one
SELECT hero_id FROM heroes
WHERE user_id = $1
`

func (q *Queries) IsHeroExists(ctx context.Context, userID int64) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, isHeroExists, userID)
	var hero_id pgtype.UUID
	err := row.Scan(&hero_id)
	return hero_id, err
}
