// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Admin struct {
	UserID int64
}

type User struct {
	UserID       int64
	Username     pgtype.Text
	Fullname     pgtype.Text
	RegisterDate pgtype.Timestamptz
}
