// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO users (user_id, username, fullname, register_date)
VALUES ($1, $2, $3, now())
ON CONFLICT (user_id) DO UPDATE
SET username = EXCLUDED.username,
    fullname = EXCLUDED.fullname
`

type CreateUserParams struct {
	UserID   int64
	Username pgtype.Text
	Fullname pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.UserID, arg.Username, arg.Fullname)
	return err
}

const getUser = `-- name: GetUser :one
SELECT user_id, username, fullname, register_date FROM users
WHERE user_id == $1
`

func (q *Queries) GetUser(ctx context.Context, userID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, userID)
	var i User
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Fullname,
		&i.RegisterDate,
	)
	return i, err
}

const isUserExists = `-- name: IsUserExists :one
SELECT user_id FROM users
WHERE user_id == $1
`

func (q *Queries) IsUserExists(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, isUserExists, userID)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}
